Shop.WebUI/Controllers/ProductCategoryController.cs
using Shop.Core.Models;
using Shop.DataAccess.InMemory;
using Shop.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.WebUI.Controllers
{
    public class ProductCategoryController : Controller
    {
        internal IRepository<ProductCategory> context;

        public ProductCategoryController()
        {
            context = new SQLRepository<ProductCategory>(new MyContext());
        }

        // GET: ProductManager
        public ActionResult Index()
        {
            List<ProductCategory> productscat = context.Collection().ToList();
            return View(productscat);
        }

        public ActionResult Create()
        {
            ProductCategory pcat = new ProductCategory();
            return View(pcat);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCategory pcat)
        {
            if (!ModelState.IsValid)
            {
                return View(pcat);
            }
            else
            {
                context.Insert(pcat);
                context.Commit();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                ProductCategory pcat = context.FindById(id);
                if (pcat == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(pcat);
                }
            }
            catch (Exception)
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategory pcat)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(pcat);
                    context.Commit();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }

            }
            else
            {
                return View(pcat.Id);
            }

        }

        public ActionResult Delete(int id)
        {
            try
            {
                ProductCategory pcat = context.FindById(id);
                if (pcat == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(pcat);
                }
            }
            catch (Exception)
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    context.Delete(id);
                    context.Commit();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }

            }
            else
            {
                return View(id);
            }

        }
    }
}

Shop.WebUI/Controllers/ProductManagerController.cs
using Shop.Core.Models;
using Shop.Core.ViewModels;
using Shop.DataAccess.InMemory;
using Shop.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.WebUI.Controllers
{
    public class ProductManagerController : Controller
    {
        internal IRepository<Product> context;
        internal IRepository<ProductCategory> contextCategory;

        public ProductManagerController()
        {
            context = new SQLRepository<Product>(new MyContext());
            contextCategory = new SQLRepository<ProductCategory>(new MyContext());
        }

        // GET: ProductManager
        public ActionResult Index()
        {
            List<Product> products = context.Collection().ToList();
            return View(products);
        }

        public ActionResult Create()
        {
            ProductManagerViewModel viewModel = new ProductManagerViewModel
            {
                Product = new Product(),
                ProductCategories = contextCategory.Collection().ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductManagerViewModel pvm, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(pvm);
            }
            else
            {
                if (file != null)
                {
                    pvm.Product.Image = pvm.Product.Id + Path.GetExtension(file.FileName);
                    file.SaveAs(Server.MapPath("~/Content/ProdImage/") + pvm.Product.Image);
                }
                context.Insert(pvm.Product);
                context.Commit();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                ProductManagerViewModel viewModel = new ProductManagerViewModel
                {
                    Product = context.FindById(id),
                    ProductCategories = contextCategory.Collection().ToList()
                };
                if (viewModel.Product == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(viewModel);
                }
            }
            catch (Exception)
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductManagerViewModel pvm, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        pvm.Product.Image = pvm.Product.Id + Path.GetExtension(file.FileName);
                        file.SaveAs(Server.MapPath("~/Content/ProdImage/") + pvm.Product.Image);
                    }
                    context.Update(pvm.Product);
                    context.Commit();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }

            }
            else
            {
                return View(pvm.Product.Id);
            }

        }

        public ActionResult Delete(int id)
        {
            try
            {
                Product p = context.FindById(id);
                if (p == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(p);
                }
            }
            catch (Exception)
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    context.Delete(id);
                    context.Commit();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }

            }
            else
            {
                return View(id);
            }

        }
    }
}

Shop.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Gestion des produits", "Index", "ProductManager")</li>
                    <li>@Html.ActionLink("Gestion des catégories", "Index", "ProductCategory")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["user_id"] == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    <li>@Html.ActionLink("Create account", "Create", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="container">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>